/*
 * PROJECT:   Mouri Internal Library Essentials
 * FILE:      Mile.Uefi.Specification.h
 * PURPOSE:   Definition for UEFI Specification
 *
 * LICENSE:   The MIT License
 *
 * DEVELOPER: Mouri_Naruto (Mouri_Naruto AT Outlook.com)
 */

#ifndef MILE_UEFI_SPECIFICATION
#define MILE_UEFI_SPECIFICATION

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

#include <Uefi.h>
#include <Guid\Acpi.h>
#include <Guid\Btt.h>
#include <Guid\CapsuleReport.h>
#include <Guid\Cper.h>
#include <Guid\DebugImageInfoTable.h>
#include <Guid\EventGroup.h>
#include <Guid\FileInfo.h>
#include <Guid\FileSystemInfo.h>
#include <Guid\FileSystemVolumeLabelInfo.h>
#include <Guid\FmpCapsule.h>
#include <Guid\GlobalVariable.h>
#include <Guid\Gpt.h>
#include <Guid\HardwareErrorVariable.h>
#include <Guid\HiiFormMapMethodGuid.h>
#include <Guid\HiiKeyBoardLayout.h>
#include <Guid\HiiPlatformSetupFormset.h>
#include <Guid\ImageAuthentication.h>
#include <Guid\JsonCapsule.h>
#include <Guid\MemoryAttributesTable.h>
#include <Guid\MemoryOverwriteControl.h>
#include <Guid\Mps.h>
#include <Guid\PcAnsi.h>
#include <Guid\RtPropertiesTable.h>
#include <Guid\SmBios.h>
#include <Guid\SystemResourceTable.h>
#include <Guid\WinCertificate.h>
#include <Protocol\AbsolutePointer.h>
#include <Protocol\AcpiTable.h>
#include <Protocol\AdapterInformation.h>
#include <Protocol\Arp.h>
#include <Protocol\AtaPassThru.h>
#include <Protocol\AuthenticationInfo.h>
#include <Protocol\Bis.h>
#include <Protocol\BlockIo.h>
#include <Protocol\BlockIo2.h>
#include <Protocol\BlockIoCrypto.h>
#include <Protocol\BluetoothAttribute.h>
#include <Protocol\BluetoothConfig.h>
#include <Protocol\BluetoothHc.h>
#include <Protocol\BluetoothIo.h>
#include <Protocol\BluetoothLeConfig.h>
#include <Protocol\BootManagerPolicy.h>
#include <Protocol\BusSpecificDriverOverride.h>
#include <Protocol\ComponentName.h>
#include <Protocol\ComponentName2.h>
#include <Protocol\DebugPort.h>
#include <Protocol\DebugSupport.h>
#include <Protocol\Decompress.h>
#include <Protocol\DeferredImageLoad.h>
#include <Protocol\DeviceIo.h>
#include <Protocol\DevicePath.h>
#include <Protocol\DevicePathFromText.h>
#include <Protocol\DevicePathToText.h>
#include <Protocol\DevicePathUtilities.h>
#include <Protocol\Dhcp4.h>
#include <Protocol\Dhcp6.h>
#include <Protocol\DiskIo.h>
#include <Protocol\DiskIo2.h>
#include <Protocol\Dns4.h>
#include <Protocol\Dns6.h>
#include <Protocol\DriverBinding.h>
#include <Protocol\DriverConfiguration.h>
#include <Protocol\DriverConfiguration2.h>
#include <Protocol\DriverDiagnostics.h>
#include <Protocol\DriverDiagnostics2.h>
#include <Protocol\DriverFamilyOverride.h>
#include <Protocol\DriverHealth.h>
#include <Protocol\DriverSupportedEfiVersion.h>
#include <Protocol\Eap.h>
#include <Protocol\EapConfiguration.h>
#include <Protocol\EapManagement.h>
#include <Protocol\EapManagement2.h>
#include <Protocol\Ebc.h>
#include <Protocol\EdidActive.h>
#include <Protocol\EdidDiscovered.h>
#include <Protocol\EdidOverride.h>
#include <Protocol\EraseBlock.h>
#include <Protocol\FirmwareManagement.h>
#include <Protocol\FormBrowser2.h>
#include <Protocol\Ftp4.h>
#include <Protocol\GraphicsOutput.h>
#include <Protocol\Hash.h>
#include <Protocol\Hash2.h>
#include <Protocol\HiiConfigAccess.h>
#include <Protocol\HiiConfigKeyword.h>
#include <Protocol\HiiConfigRouting.h>
#include <Protocol\HiiDatabase.h>
#include <Protocol\HiiFont.h>
#include <Protocol\HiiImage.h>
#include <Protocol\HiiImageDecoder.h>
#include <Protocol\HiiImageEx.h>
#include <Protocol\HiiPackageList.h>
#include <Protocol\HiiPopup.h>
#include <Protocol\HiiString.h>
#include <Protocol\Http.h>
#include <Protocol\HttpBootCallback.h>
#include <Protocol\HttpUtilities.h>
#include <Protocol\Ip4Config.h>
#include <Protocol\Ip4Config2.h>
#include <Protocol\Ip6Config.h>
#include <Protocol\IpSec.h>
#include <Protocol\IpSecConfig.h>
#include <Protocol\IScsiInitiatorName.h>
#include <Protocol\Kms.h>
#include <Protocol\LoadedImage.h>
#include <Protocol\LoadFile.h>
#include <Protocol\LoadFile2.h>
#include <Protocol\Mtftp4.h>
#include <Protocol\Mtftp6.h>
#include <Protocol\NetworkInterfaceIdentifier.h>
#include <Protocol\NvdimmLabel.h>
#include <Protocol\NvmExpressPassthru.h>
#include <Protocol\PartitionInfo.h>
#include <Protocol\PciIo.h>
#include <Protocol\PciRootBridgeIo.h>
#include <Protocol\Pkcs7Verify.h>
#include <Protocol\PlatformDriverOverride.h>
#include <Protocol\PlatformToDriverConfiguration.h>
#include <Protocol\PxeBaseCode.h>
#include <Protocol\PxeBaseCodeCallBack.h>
#include <Protocol\RamDisk.h>
#include <Protocol\RegularExpressionProtocol.h>
#include <Protocol\ResetNotification.h>
#include <Protocol\Rest.h>
#include <Protocol\RestEx.h>
#include <Protocol\RestJsonStructure.h>
#include <Protocol\Rng.h>
#include <Protocol\ScsiIo.h>
#include <Protocol\ScsiPassThru.h>
#include <Protocol\ScsiPassThruExt.h>
#include <Protocol\SdMmcPassThru.h>
#include <Protocol\SerialIo.h>
#include <Protocol\ServiceBinding.h>
#include <Protocol\Shell.h>
#include <Protocol\ShellDynamicCommand.h>
#include <Protocol\ShellParameters.h>
#include <Protocol\SimpleFileSystem.h>
#include <Protocol\SimplePointer.h>
#include <Protocol\SimpleTextIn.h>
#include <Protocol\SimpleTextInEx.h>
#include <Protocol\SimpleTextOut.h>
#include <Protocol\SmartCardEdge.h>
#include <Protocol\SmartCardReader.h>
#include <Protocol\StorageSecurityCommand.h>
#include <Protocol\Supplicant.h>
#include <Protocol\TapeIo.h>
#include <Protocol\Tcp4.h>
#include <Protocol\Tcp6.h>
#include <Protocol\Timestamp.h>
#include <Protocol\Tls.h>
#include <Protocol\TlsConfig.h>
#include <Protocol\Udp4.h>
#include <Protocol\Udp6.h>
#include <Protocol\UfsDeviceConfig.h>
#include <Protocol\UgaDraw.h>
#include <Protocol\UgaIo.h>
#include <Protocol\UnicodeCollation.h>
#include <Protocol\Usb2HostController.h>
#include <Protocol\UsbFunctionIo.h>
#include <Protocol\UsbHostController.h>
#include <Protocol\UsbIo.h>
#include <Protocol\UserCredential.h>
#include <Protocol\UserCredential2.h>
#include <Protocol\UserManager.h>
#include <Protocol\VlanConfig.h>
#include <Protocol\WiFi.h>
#include <Protocol\WiFi2.h>
#include <IndustryStandard\Acpi.h>
#include <IndustryStandard\AlertStandardFormatTable.h>
#include <IndustryStandard\ArmErrorSourceTable.h>
#include <IndustryStandard\Atapi.h>
#include <IndustryStandard\Bluetooth.h>
#include <IndustryStandard\Bmp.h>
#include <IndustryStandard\Cxl.h>
#include <IndustryStandard\DebugPort2Table.h>
#include <IndustryStandard\DebugPortTable.h>
#include <IndustryStandard\Dhcp.h>
#include <IndustryStandard\DmaRemappingReportingTable.h>
#include <IndustryStandard\ElTorito.h>
#include <IndustryStandard\Emmc.h>
#include <IndustryStandard\HighPrecisionEventTimerTable.h>
#include <IndustryStandard\Http11.h>
#include <IndustryStandard\IoRemappingTable.h>
#include <IndustryStandard\Ipmi.h>
#include <IndustryStandard\IScsiBootFirmwareTable.h>
#include <IndustryStandard\LegacyBiosMpTable.h>
#include <IndustryStandard\LowPowerIdleTable.h>
#include <IndustryStandard\Mbr.h>
#include <IndustryStandard\MemoryMappedConfigurationSpaceAccessTable.h>
#include <IndustryStandard\MemoryOverwriteRequestControlLock.h>
#include <IndustryStandard\Nvme.h>
#include <IndustryStandard\Pci.h>
#include <IndustryStandard\PeImage.h>
#include <IndustryStandard\Scsi.h>
#include <IndustryStandard\Sd.h>
#include <IndustryStandard\SdramSpd.h>
#include <IndustryStandard\SerialPortConsoleRedirectionTable.h>
#include <IndustryStandard\ServiceProcessorManagementInterfaceTable.h>
#include <IndustryStandard\SmBios.h>
#include <IndustryStandard\SmBus.h>
#include <IndustryStandard\Spdm.h>
#include <IndustryStandard\TcpaAcpi.h>
#include <IndustryStandard\Tls1.h>
#include <IndustryStandard\Udf.h>
#include <IndustryStandard\Usb.h>
#include <IndustryStandard\WatchdogActionTable.h>
#include <IndustryStandard\WatchdogResourceTable.h>
#include <IndustryStandard\WindowsSmmSecurityMitigationTable.h>
#include <IndustryStandard\WindowsUxCapsule.h>
#include <Register\Amd\Cpuid.h>
#include <Register\Amd\Fam17Msr.h>
#include <Register\Amd\Ghcb.h>
#include <Register\Amd\Msr.h>
#include <Register\Intel\Cpuid.h>
#include <Register\Intel\LocalApic.h>
#include <Register\Intel\Microcode.h>
#include <Register\Intel\Msr.h>
#include <Register\Intel\SmramSaveStateMap.h>
#include <Register\Intel\StmApi.h>
#include <Uefi\UefiAcpiDataTable.h>
#include <Uefi\UefiGpt.h>
#include <Uefi\UefiInternalFormRepresentation.h>
#include <Uefi\UefiPxe.h>

#ifdef __cplusplus
}
#endif // __cplusplus

#ifndef __cplusplus
#include <IndustryStandard\TcgPhysicalPresence.h>
#include <IndustryStandard\TcgStorageOpal.h>
#include <IndustryStandard\Tpm2Acpi.h>
#include <IndustryStandard\TpmPtp.h>
#include <IndustryStandard\TpmTis.h>
#include <Protocol\Tcg2Protocol.h>
#include <Protocol\TcgService.h>
#include <Protocol\TrEEProtocol.h>
#endif // !__cplusplus

#endif // !MILE_UEFI_SPECIFICATION
